package corbaConversion;


/**
* corbaConversion/IConversionRemoteOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Conversion.idl
* mercredi 29 novembre 2023 22 h 53 WAT
*/

public interface IConversionRemoteOperations 
{
  double convertirMontant (double mt);
} // interface IConversionRemoteOperations
